Update menu_inst

diff --git a/menu_inst b/menu_inst
--- a/menu_inst
+++ b/menu_inst
@@ -1048,7 +1048,7 @@ echo -e "$barra\n "Parado con exitó")\n$barra"
 rm /etc/adm-lite/edbypass
 return 0
 }
-echo -e "$barra\n "TCP Bypass VIP")\n$barra"
+echo -e "$barra\n ("TCP Bypass VIP")\n$barra"
 chmod +x ./overtcp
 ./overtcp || { 
 echo -e "$barra"
@@ -1056,60 +1056,60 @@ return 1
 }
 touch /etc/adm-lite/edbypass
 tput cuu1 && tput dl1
-echo -e "$barra\n "Procedimento Concluido")\n$barra"
+echo -e "$barra\n ("Procedimento Concluido")\n$barra"
 return 0
 }
 
 ssl_stunel () {
 [[ $(mportas|grep stunnel4|head -1) ]] && {
 echo -e "$barra"
-echo -e "\033[1;33m "Parando Stunnel")"
+echo -e "\033[1;33m ("Parando Stunnel")"
 echo -e "$barra"
 fun_bar "apt-get purge stunnel4 -y"
 echo -e "$barra"
-echo -e "\033[1;33m "Parado Con exitó!")"
+echo -e "\033[1;33m ("Parado Con exitó!")"
 echo -e "$barra"
 return 0
 }
 echo -e "$barra"
-echo -e "\033[1;36m "SSL Stunnel")"
+echo -e "\033[1;36m ("SSL Stunnel")"
 echo -e "$barra"
-echo -e "\033[1;33m "Selecione Un Puerto De Redirecionamento Interna")"
-echo -e "\033[1;33m "Es decir, un puerto en su servidor para SSL")"
+echo -e "\033[1;33m ("Selecione Un Puerto De Redirecionamento Interna")"
+echo -e "\033[1;33m ("Es decir, un puerto en su servidor para SSL")"
 echo -e "$barra"
          while true; do
          echo -ne "\033[1;37m"
          read -p " Local-Port: " portx
          if [[ ! -z $portx ]]; then
              if [[ $(echo $portx|grep [0-9]) ]]; then
-                [[ $(mportas|grep $portx|head -1) ]] && break || echo -e "\033[1;31m $(source trans -b pt:${id} "Porta Invalida")"
+                [[ $(mportas|grep $portx|head -1) ]] && break || echo -e "\033[1;31m ("Puerto Invalido")"
              fi
          fi
          done
 echo -e "$barra"
 DPORT="$(mportas|grep $portx|awk '{print $2}'|head -1)"
-echo -e "\033[1;33m "Ahora prestamos Saber qué puerto el SSL, va a escuchar")"
+echo -e "\033[1;33m ("Ahora el Puerto SSL, que va a escuchar")"
 echo -e "$barra"
     while true; do
     read -p " Listen-SSL: " SSLPORT
     [[ $(mportas|grep $SSLPORT) ]] || break
-    echo -e "\033[1;33m "El puerto seleccionado ya se encuentra en uso")"
+    echo -e "\033[1;33m ("El puerto seleccionado ya se encuentra en uso")"
     unset SSLPORT
 	echo -e "$barra"
 	return 0
     done
 echo -e "$barra"
-echo -e "\033[1;33m "Instalando SSL")"
+echo -e "\033[1;33m ("Instalando SSL")"
 echo -e "$barra"
 fun_bar "apt-get install stunnel4 -y"
 echo -e "cert = /etc/stunnel/stunnel.pem\nclient = no\nsocket = a:SO_REUSEADDR=1\nsocket = l:TCP_NODELAY=1\nsocket = r:TCP_NODELAY=1\n\n[stunnel]\nconnect = 127.0.0.1:${DPORT}\naccept = ${SSLPORT}" > /etc/stunnel/stunnel.conf
 openssl genrsa -out key.pem 2048 > /dev/null 2>&1
-(echo br; echo br; echo uss; echo speed; echo adm; echo ultimate; echo @admultimate)|openssl req -new -x509 -key key.pem -out cert.pem -days 1095 > /dev/null 2>&1
+(echo br; echo br; echo uss; echo speed; echo adm; echo mscperu; echo @mscperu)|openssl req -new -x509 -key key.pem -out cert.pem -days 1095 > /dev/null 2>&1
 cat key.pem cert.pem >> /etc/stunnel/stunnel.pem
 sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/stunnel4
 service stunnel4 restart > /dev/null 2>&1
 echo -e "$barra"
-echo -e "\033[1;33m "INSTALADO CON EXITO")"
+echo -e "\033[1;33m ("INSTALADO CON EXITO")"
 echo -e "$barra"
 return 0
 }
@@ -1121,7 +1121,7 @@ echo -e "$barra"
 read -p " [ s | n ]: " up_load
 echo -e "$barra"
    [[ "$up_load" = @(s|S|y|Y) ]] && bash /etc/adm-lite/instalar_wep || {
-   echo -e "${cor[2]}$(source trans -b pt:${id} "Instalación canselada")"
+   echo -e "${cor[2]}$(source trans -b pt:${id} "Instalación cancelado")"
    echo -e "$barra"
    }
 }
